// Tauranga Harbour tide-prediction module — harmonic constituent model.
// AUTO-GENERATED by tide/fit.mjs — do not hand-edit the constants below.
//
// Source data: LINZ (Land Information New Zealand) official tide tables for
// Tauranga (port 073), tauranga_2023..2027.csv. Heights are metres above
// CHART DATUM (not mean sea level). A shipping app MUST carry LINZ
// attribution — see docs/tide-validation.md.
//
// Model: h(t) = Z0 + sum_i f_i(t) * A_i * cos(omega_i * t - phi_i - u_i(t))
// t = hours since EPOCH_MS (2023-01-01T00:00:00Z), omega_i in rad/hour.
// f_i(t), u_i(t) are analytic nodal (18.6-year lunar node) corrections —
// NOT fitted (unresolvable from a 5-year record) — evaluated per timestep
// from the lunar node longitude N(t). See fit.mjs for the derivation and
// which constituents share a parent species' correction (documented
// simplification for satellites of M2/O1 without lunar-perigee dependence).
//
// Round-2 validation (fit on 2023+2024+2025+2027, held out 2026 as an
// INTERIOR year — a stronger test than extrapolating past the record):
//   HEADLINE timing error: mean 9.45 min, max 29.68 min
//   height RMSE at turning points: 0.0313 m (max 0.0789 m)
//   height RMSE at mid-tide (proxy): 0.1732 m (max 0.4039 m)
// Full numbers, worst-case tables and methodology caveats: docs/tide-validation.md.
//
// 23 of 31 candidate constituents survived the
// >=5mm amplitude threshold and are shipped below (see docs/tide-validation.md for
// the dropped list).
//
// These shipping coefficients are refit on ALL FIVE available years
// (2023-2027) for slightly better accuracy than the held-out validation run.

export const EPOCH_MS = 1672531200000;
const J2000_MS = 946728000000;
const DEG2RAD = Math.PI / 180;
export const Z0 = 1.0540609877941658;

export const CONSTITUENTS = [
  { name: "M2", omega: 0.5058680455404585, amplitude: 0.6552741298331658, phase: 1.1297598754302625 },
  { name: "S2", omega: 0.5235987755982988, amplitude: 0.10584599010802048, phase: -1.736349998664027 },
  { name: "N2", omega: 0.49636692687820694, amplitude: 0.16657539001542884, phase: 2.3114191625025593 },
  { name: "K2", omega: 0.5250323366860095, amplitude: 0.019976446339386857, phase: 1.0724887071596791 },
  { name: "K1", omega: 0.26251617706965097, amplitude: 0.052850016091018616, phase: -0.25497719722399614 },
  { name: "O1", omega: 0.24335186847080756, amplitude: 0.020922609656975684, phase: -2.6073115508241624 },
  { name: "P1", omega: 0.2610825985286479, amplitude: 0.016849597011402734, phase: 0.14308503380606707 },
  { name: "M4", omega: 1.011736091080917, amplitude: 0.06202110172262469, phase: 1.8674877801998344 },
  { name: "MS4", omega: 1.0294668211387574, amplitude: 0.006410458812507479, phase: -1.2941095613608067 },
  { name: "MN4", omega: 1.0022349375120805, amplitude: 0.010238216005212906, phase: 3.0733538462873073 },
  { name: "Mm", omega: 0.009501136115544132, amplitude: 0.02122478802805712, phase: 1.5598071778113904 },
  { name: "2N2", omega: 0.4868657907626628, amplitude: 0.015732213591737272, phase: -2.828770510311402 },
  { name: "MU2", omega: 0.48813731548261824, amplitude: 0.004584518119756976, phase: 0.5874796647700493 },
  { name: "NU2", omega: 0.49763845159816233, amplitude: 0.0430704203558179, phase: 3.018711522523577 },
  { name: "L2", omega: 0.5153691816560027, amplitude: 0.05131553199608894, phase: 2.4240039914847222 },
  { name: "T2", omega: 0.5228820212343823, amplitude: 0.007397787796435036, phase: -0.9050202951174641 },
  { name: "LDA2", omega: 0.5140976394827548, amplitude: 0.024487165018789125, phase: 1.8726415536787289 },
  { name: "J1", omega: 0.2720172957319026, amplitude: 0.005638390248776675, phase: -1.1956686768499358 },
  { name: "M6", omega: 1.5176041366213757, amplitude: 0.06629334252854092, phase: -3.117395852923498 },
  { name: "2MS6", omega: 1.5353348666792161, amplitude: 0.02083695688162504, phase: 1.844935959991826 },
  { name: "MK3", omega: 0.7683842226101095, amplitude: 0.00938298908035815, phase: 1.255582226441998 },
  { name: "MSF", omega: 0.017730730057840313, amplitude: 0.008274410648431615, phase: 0.6068961366376181 },
  { name: "SA", omega: 0.0007167892705015512, amplitude: 0.044370243342402686, phase: 1.88286173121287 },
];

// ---- Nodal correction (see fit.mjs header comment for full derivation) ----
function nodalAngleRad(tHours) {
  const ms = EPOCH_MS + tHours * 3600000;
  const days = (ms - J2000_MS) / 86400000;
  const T = days / 36525;
  const omegaDeg = 125.04452 - 1934.136261 * T;
  return omegaDeg * DEG2RAD;
}

function nodalFactors(N) {
  const cosN = Math.cos(N), sinN = Math.sin(N);
  const cos2N = Math.cos(2 * N), sin2N = Math.sin(2 * N);
  const cos3N = Math.cos(3 * N), sin3N = Math.sin(3 * N);
  const fM2 = 1 - 0.037 * cosN;
  const uM2 = (-2.14 * sinN) * DEG2RAD;
  const fK1 = 1.0060 + 0.1150 * cosN - 0.0088 * cos2N + 0.0006 * cos3N;
  const uK1 = (-8.86 * sinN + 0.68 * sin2N - 0.07 * sin3N) * DEG2RAD;
  const fO1 = 1.0089 + 0.1871 * cosN - 0.0147 * cos2N + 0.0014 * cos3N;
  const uO1 = (10.80 * sinN - 1.34 * sin2N + 0.19 * sin3N) * DEG2RAD;
  const fK2 = 1.0246 + 0.2863 * cosN + 0.0083 * cos2N - 0.0015 * cos3N;
  const uK2 = (-17.74 * sinN + 0.68 * sin2N - 0.04 * sin3N) * DEG2RAD;
  const fJ1 = 1.0129 + 0.1676 * cosN - 0.0170 * cos2N + 0.0016 * cos3N;
  const uJ1 = (-12.94 * sinN + 1.34 * sin2N - 0.19 * sin3N) * DEG2RAD;
  const fOO1 = 1.1027 + 0.6504 * cosN + 0.0317 * cos2N;
  const uOO1 = (-36.68 * sinN + 2.72 * sin2N) * DEG2RAD;
  const fMm = 1 - 0.130 * cosN + 0.0013 * cos2N;
  const uMm = 0;
  const fMf = 1.0429 + 0.4135 * cosN - 0.004 * cos2N;
  const uMf = (-23.74 * sinN + 2.68 * sin2N - 0.38 * sin3N) * DEG2RAD;
  return { fM2, uM2, fK1, uK1, fO1, uO1, fK2, uK2, fJ1, uJ1, fOO1, uOO1, fMm, uMm, fMf, uMf };
}

const NODAL_MAP = {
  M2: nf => [nf.fM2, nf.uM2], S2: () => [1, 0], N2: nf => [nf.fM2, nf.uM2],
  K2: nf => [nf.fK2, nf.uK2], K1: nf => [nf.fK1, nf.uK1], O1: nf => [nf.fO1, nf.uO1],
  P1: () => [1, 0], Q1: nf => [nf.fO1, nf.uO1],
  M4: nf => [nf.fM2 * nf.fM2, 2 * nf.uM2], MS4: nf => [nf.fM2, nf.uM2],
  MN4: nf => [nf.fM2 * nf.fM2, 2 * nf.uM2], Mf: nf => [nf.fMf, nf.uMf], Mm: nf => [nf.fMm, nf.uMm],
  SSA: () => [1, 0], '2N2': nf => [nf.fM2, nf.uM2], MU2: nf => [nf.fM2, nf.uM2],
  NU2: nf => [nf.fM2, nf.uM2], L2: nf => [nf.fM2, nf.uM2], T2: () => [1, 0],
  LDA2: nf => [nf.fM2, nf.uM2], J1: nf => [nf.fJ1, nf.uJ1], M1: nf => [nf.fO1, nf.uO1],
  OO1: nf => [nf.fOO1, nf.uOO1], RHO1: nf => [nf.fO1, nf.uO1], SIGMA1: nf => [nf.fO1, nf.uO1],
  M6: nf => [nf.fM2 * nf.fM2 * nf.fM2, 3 * nf.uM2], '2MS6': nf => [nf.fM2 * nf.fM2, 2 * nf.uM2],
  MK3: nf => [nf.fM2 * nf.fK1, nf.uM2 + nf.uK1], S4: () => [1, 0],
  MSF: nf => [nf.fM2, -nf.uM2], SA: () => [1, 0],
};

function hoursSinceEpoch(date) {
  return (date.getTime() - EPOCH_MS) / 3600000;
}

function heightAtHours(t) {
  const N = nodalAngleRad(t);
  const nf = nodalFactors(N);
  let h = Z0;
  for (const c of CONSTITUENTS) {
    const [f, u] = NODAL_MAP[c.name](nf);
    h += f * c.amplitude * Math.cos(c.omega * t - c.phase - u);
  }
  return h;
}

function derivativeAtHours(t) {
  const N = nodalAngleRad(t);
  const nf = nodalFactors(N);
  let d = 0;
  for (const c of CONSTITUENTS) {
    const [f, u] = NODAL_MAP[c.name](nf);
    d += -f * c.amplitude * c.omega * Math.sin(c.omega * t - c.phase - u);
  }
  return d;
}

/** Predicted tide height (metres above chart datum) at an instant. */
export function predict(date) {
  return heightAtHours(hoursSinceEpoch(date));
}

/** Predicted tide curve between two instants, sampled every stepMinutes. */
export function predictRange(startDate, endDate, stepMinutes) {
  const out = [];
  const stepMs = stepMinutes * 60000;
  for (let ms = startDate.getTime(); ms <= endDate.getTime(); ms += stepMs) {
    const t = (ms - EPOCH_MS) / 3600000;
    out.push({ t: new Date(ms), h: heightAtHours(t) });
  }
  return out;
}

function refineExtremum(loT, hiT, dLo) {
  let lo = loT, hi = hiT;
  for (let i = 0; i < 40; i++) {
    const mid = (lo + hi) / 2;
    const dMid = derivativeAtHours(mid);
    if ((dLo <= 0 && dMid > 0) || (dLo >= 0 && dMid < 0)) hi = mid;
    else { lo = mid; dLo = dMid; }
  }
  return (lo + hi) / 2;
}

/**
 * Upcoming high/low turning points from a given instant onward.
 * Returns [{ time: Date, height: number, type: 'high'|'low' }, ...]
 */
export function nextTurningPoints(date, count = 4) {
  const t0 = hoursSinceEpoch(date);
  const stepH = 2 / 60; // 2-minute coarse scan
  const results = [];
  let prevT = t0, prevD = derivativeAtHours(t0);
  const maxScanH = 24 * 30; // safety bound: 30 days
  for (let t = t0 + stepH; t <= t0 + maxScanH && results.length < count; t += stepH) {
    const d = derivativeAtHours(t);
    if ((prevD > 0 && d <= 0) || (prevD < 0 && d >= 0)) {
      const tExt = refineExtremum(prevT, t, prevD);
      const h = heightAtHours(tExt);
      const type = prevD > 0 ? 'high' : 'low';
      results.push({ time: new Date(EPOCH_MS + tExt * 3600000), height: h, type });
    }
    prevT = t; prevD = d;
  }
  return results;
}
