import fs from 'fs';
import sharp from 'sharp';
const tide = fs.readFileSync('../tide/tauranga-tide.js','utf8').replace(/^export /gm,'');
const uri = (f,m) => `data:${m};base64,` + fs.readFileSync(f).toString('base64');

// ---- page-copy generation --------------------------------------------------------------
// The 5120px/q90 basemap originals and the losslessly-compressed-but-large field/flow rasters
// blow the page's size budget (~22MB) if embedded verbatim. Cheap, reproducible, disk-cached
// "page copies" bring them in: basemaps recompressed to 4096px/q80 JPEG (mozjpeg), field-v3 and
// flow re-encoded PNG at a tighter compression setting (same pixels, smaller file). The 5120px
// JPEG/full-res PNG originals on disk are never touched or overwritten.
//
// TRAP: sharp's PNG `effort` option (any value 1-10, this build's sharp/libvips 0.35.3) silently
// corrupts RGBA pixel data wherever alpha < 255 — it looks like an unpremultiply bug in that
// code path, not a filter/compression-level issue (confirmed: `compressionLevel` and
// `adaptiveFiltering` alone round-trip byte-identical; adding `effort` at ANY value, even 1,
// does not). field-v3.png's alpha channel is the height's low byte, not transparency, so this
// silently wrecked the sub-millimetre precision this whole round exists to protect. Never pass
// `effort` to `.png()` on a buffer that has a real (non-transparency) alpha channel.
function needsRebuild(src, dst) {
  if (!fs.existsSync(dst)) return true;
  return fs.statSync(src).mtimeMs > fs.statSync(dst).mtimeMs;
}
async function pageJpeg(src, dst, size=4096, quality=80) {
  if (!needsRebuild(src, dst)) return;
  const buf = await sharp(src).resize(size, size, {fit:'fill'}).jpeg({quality, mozjpeg:true}).toBuffer();
  fs.writeFileSync(dst, buf);
}
async function pagePng(src, dst, size=null) {
  if (!needsRebuild(src, dst)) return;
  let img = sharp(src);
  if (size) img = img.resize(size, size, {fit:'fill', kernel:'mitchell'});
  // compressionLevel+adaptiveFiltering only — see the `effort` trap above.
  const buf = await img.png({compressionLevel:9, adaptiveFiltering:true}).toBuffer();
  fs.writeFileSync(dst, buf);
}

// Fused is the new default (LINZ detail + Sentinel-2 colour — see
// research/overnight-2026-07-27/imagery/README.md). LINZ aerial (original) and Sentinel-2 are
// shipped alongside it per the brief; fusegrade rides along too since it fits budget with room
// to spare. `base-graded.jpg` (the fifth J1a candidate) does technically also fit under the
// 22MB ceiling but only by ~150KB — too close to the edge given flow.png (a third texture with
// its own, less predictable compression ratio) can be regenerated by another job in this round.
// Left out for a comfortable safety margin; trivial to re-add (uncomment) if the final budget
// check shows enough headroom.
// ARTIFACT=1 builds a slimmer tidemap-artifact.html: the artifact host caps uploads at 16 MB,
// so basemaps drop to 3072/q78, flow to 2048, and the fourth basemap stays home. The field is
// NEVER downsized or recompressed differently — it is the 16-bit data. iPad/local keep full fat.
const ARTIFACT = !!process.env.ARTIFACT;
const BM_SIZE = ARTIFACT ? 3072 : 4096, BM_Q = ARTIFACT ? 78 : 80;
const pfx = ARTIFACT ? 'data/apage-' : 'data/page-';
const BASEMAPS = [
  ['Fused (LINZ + Sentinel-2)', 'data/base-fused.jpg',     pfx+'fused.jpg'],
  ['LINZ aerial (original)',    'data/base-aerial.jpg',    pfx+'aerial.jpg'],
  ['Sentinel-2 true colour',    'data/base-s2fresh.jpg',   pfx+'s2fresh.jpg'],
  ...(ARTIFACT ? [] : [['Fused + grade', 'data/base-fusegrade.jpg', pfx+'fusegrade.jpg']]),
  // ['LINZ aerial, regraded', 'data/base-graded.jpg', pfx+'graded.jpg'],
];
for (const [,src,dst] of BASEMAPS) await pageJpeg(src, dst, BM_SIZE, BM_Q);
await pagePng('data/field-v3.png', 'data/page-field.png');          // no resize — 16-bit precision
await pagePng('data/flow.png', pfx+'flow.png', ARTIFACT ? 2048 : 2560);
await pagePng('data/relief.png', pfx+'relief.png', ARTIFACT ? 1024 : 1280);  // gentle low-freq relief
// City lights (R=core, G=corona, B=coolness — see build-citylights-points.mjs). Already a tight
// 4096px/~1.9MB PNG at compressionLevel 9, mostly-black, so local/iPad ships it as-is. The 16MB
// ARTIFACT cap has no equivalent headroom (measured: full-size lights put ARTIFACT at 16.19MB,
// over budget, even with field-v3's B-channel retirement's savings already counted) so ARTIFACT
// gets a 3072px downsize through the normal pagePng path — same pfx pattern as flow/relief.
const lightsPage = ARTIFACT ? pfx+'citylights.png' : 'data/citylights-points.png';
if (ARTIFACT) await pagePng('data/citylights-points.png', lightsPage, 3072);

// The basemaps and the field/flow go into the DOCUMENT as <img>, not into the module source.
// A multi-megabyte data URI inside <script type="module"> silently never executes in some
// engines — the script element is there, 6.8 M chars long, and nothing ever runs.
const tags = BASEMAPS.map(([name,,page],i)=>
  `<img id="img_base${i}" data-name="${name}" alt="" decoding="async" src="${uri(page,'image/jpeg')}">`)
  .concat(`<img id="img_field" alt="" decoding="async" src="${uri('data/page-field.png','image/png')}">`)
  .concat(`<img id="img_flow" alt="" decoding="async" src="${uri(pfx+'flow.png','image/png')}">`)
  .concat(`<img id="img_relief" alt="" decoding="async" src="${uri(pfx+'relief.png','image/png')}">`)
  .concat(`<img id="img_lights" alt="" decoding="async" src="${uri(lightsPage,'image/png')}">`)
  .join('\n');

const html = fs.readFileSync('template-v2.html','utf8')
  .replace('__TIDE_MODULE__', tide)
  .replace('__IMG_TAGS__', tags);
if (html.includes('__IMG_TAGS__') || html.includes('__TIDE_MODULE__')) throw new Error('a placeholder was not replaced');
if (/LINZ_KEY|key=[0-9a-f]{20,}/.test(html)) throw new Error('an API key reached the published page');
// lastIndexOf, not a regex: the comment above the assets div quotes the tag literally.
const script = html.slice(html.lastIndexOf('<script type="module">'));
if (script.length > 400000) throw new Error(`module source is ${script.length} chars — payload leaked back into the script`);
// The module must PARSE. A stray backtick in a GLSL comment ends the shader template literal
// early and the whole module dies with a SyntaxError the page never surfaces — it cost this
// session a round trip to the browser to find. AsyncFunction accepts top-level await; the
// module has no import/export, so a parse here proves the browser can parse it too.
const modSrc = script.slice(script.indexOf('>')+1, script.lastIndexOf('</script>'));
try { new (Object.getPrototypeOf(async function(){}).constructor)(modSrc); }
catch (e) { throw new Error(`module source does not parse: ${e.message}`); }
fs.writeFileSync(ARTIFACT ? 'tidemap-artifact.html' : 'tidemap-v2.html', html);
const MB = 1e6;
console.log(`built ${(html.length/MB).toFixed(2)} MB total, module source ${(script.length/1024).toFixed(0)} kB`);
// Budget raised 22 -> 23 MB (2026-07-28): the relief bake doubled to 4096 under Ryan's
// max-detail directive (+~5 MB). Local/iPad only — the ARTIFACT build has its own 16 MB
// ceiling and still downsizes.
if (html.length/MB > 23) console.warn(`WARNING: ${(html.length/MB).toFixed(2)} MB exceeds the 23 MB page-size budget`);
